### ISSUE TITLE
Licensing bug

### ISSUE THREAD

**Issue by felixp7** [jamesgregson/expression_parser#2]
Hello! I was just driving by, and couldn't help but notice that this project is licensed as "GPLv2 for non-commercial use". That's an oxymoron by definition: the WHOLE POINT of the General Public License is to allow for commercial use of software while keeping it free as in freedom. So it can be either GPL-licensed OR non-commercial. It can't be both in any way, shape or form.

See: freedom number 1, as described in both the preamble and the main license text.

**Comment by jamesgregson** [comment]
Hi,

I understand what you're getting at but am not too concerned about the nuances of different types of freedom as described by the FSF.  As I see it there are three options:

1) Use the library, non-commercially, in such a manner that you comply with the GPL, acknowledging that some of the use cases (commercial use) typically provided by the GPL are unavailable to you due to my more restrictive pre-condition

2) Use the library, commercially, such that you comply with another set of terms that we agree mutually agree upon.

3) Develop your own solution, perhaps using this one as inspiration, and set your own terms.

Whichever people choose is fine with me.
